// Update the interface at the top of the file
export interface MediaItem {
  src: string
  alt: string
  type?: 'image' | 'video'
  width?: number
  height?: number
}

export const travelStats = [
  { label: 'Countries', value: '8' },
  { label: 'Continents', value: '2' },
  { label: 'Solo Trips', value: '8' },
  { label: 'Photos', value: '∞' },
  { label: 'Memories', value: '∞' },
  { label: 'Next Stop', value: '???' },
]

// Add more photos to the array
export const travelPhotos: MediaItem[] = [
  {
    src: '/static/images/uae/zayed.jpg',
    width: 4032,
    height: 3024,
    alt: 'Sheikh Zayed Grand Mosque in Abu Dhabi 🇦🇪',
  },
  {
    src: '/static/images/uae/topgolf.jpg',
    width: 2160,
    height: 3840,
    alt: 'Topgolf in Dubai 🇦🇪',
  },
  {
    src: '/static/images/uae/topgolf1.jpg',
    width: 4032,
    height: 3024,
    alt: 'Showcasing my golf skills',
  },
  {
    src: '/static/images/uae/burjalarab.jpg',
    width: 3024,
    height: 4032,
    alt: 'Burj Al Arab in Dubai 🇦🇪',
  },
  {
    src: '/static/images/uae/burjkhalifa1.jpg',
    width: 3024,
    height: 4032,
    alt: 'Burj Khalifa in Dubai 🇦🇪',
  },
  {
    src: '/static/images/uae/burjkhalifa2.jpg',
    width: 2268,
    height: 4032,
    alt: 'Burj Khalifa in Dubai 🇦🇪',
  },
  {
    src: '/static/images/uae/burjkhalifa3.jpg',
    width: 3024,
    height: 4032,
    alt: 'Burj Khalifa in Dubai 🇦🇪',
  },
  {
    src: '/static/images/turkiye/istanbulstreet.jpg',
    width: 1170,
    height: 2080,
    alt: 'Beautiful street of Istanbul',
  },
  {
    src: '/static/images/turkiye/istanbulstreet1.jpg',
    width: 3520,
    height: 1980,
    alt: 'Taskim Square in Istanbul',
  },
  {
    src: '/static/images/turkiye/istanbulstreet2.jpg',
    width: 3024,
    height: 4032,
    alt: 'Istanbul street view',
  },
  {
    src: '/static/images/turkiye/bluemosque.jpg',
    width: 1170,
    height: 2080,
    alt: 'Blue Mosque in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/grandbazaar1.jpg',
    width: 3520,
    height: 1980,
    alt: 'Spice Bazaar in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/grandbazar.jpg',
    width: 3520,
    height: 1980,
    alt: 'Grand Bazaar in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/hagiasofia.jpg',
    width: 1170,
    height: 2080,
    alt: 'Hagia Sophia in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/hagiasofia1.jpg',
    width: 1170,
    height: 2080,
    alt: 'Inside view of Hagia Sophia',
  },
  {
    src: '/static/images/turkiye/hagiasofia2.jpg',
    width: 1170,
    height: 2080,
    alt: 'Hagia Sophia from gate of Blue Mosque',
  },
  {
    src: '/static/images/turkiye/hagiasofia3.jpg',
    width: 3520,
    height: 1980,
    alt: 'Friday Prayer at Hagia Sophia 🇹🇷',
  },
  {
    src: '/static/images/turkiye/hagiasofia4.jpg',
    width: 3520,
    height: 1980,
    alt: 'Hagia Sophia in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/hagiasofia5.jpg',
    width: 2268,
    height: 4032,
    alt: 'After Friday Prayer at Hagia Sophia',
  },
  {
    src: '/static/images/turkiye/hagiasofia6.jpg',
    width: 1170,
    height: 2080,
    alt: 'Hagia Sophia in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/hagiasofia7.jpg',
    width: 1170,
    height: 2080,
    alt: 'Hagia Sophia in night view',
  },
  {
    src: '/static/images/turkiye/istanbul.jpg',
    width: 1170,
    height: 2080,
    alt: 'Beautiful view of Istanbul from the top of the Galata Tower',
  },
  {
    src: '/static/images/turkiye/istanbul1.jpg',
    width: 3840,
    height: 2160,
    alt: 'Bosphorus Strait from terrace of my hotel',
  },
  {
    src: '/static/images/turkiye/istanbul2.jpg',
    width: 1170,
    height: 2080,
    alt: 'Fishing on the Bosphorus Strait',
  },
  {
    src: '/static/images/turkiye/istanbulairport.jpg',
    width: 1170,
    height: 2080,
    alt: 'New Istanbul International Airport',
  },
  {
    src: '/static/images/turkiye/dolmabache.jpg',
    width: 1170,
    height: 2080,
    alt: 'Dolmabahçe Mosque',
  },
  {
    src: '/static/images/turkiye/bluemosque1.jpg',
    width: 1170,
    height: 2080,
    alt: 'Night view of Blue Mosque in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/galatatower.jpg',
    width: 1170,
    height: 2080,
    alt: 'Galata Tower 🇹🇷',
  },
  {
    src: '/static/images/turkiye/galatatower1.jpg',
    width: 2316,
    height: 3088,
    alt: 'Me with Galata Tower 🇹🇷',
  },
  {
    src: '/static/images/turkiye/bosphorus.jpg',
    width: 1170,
    height: 2080,
    alt: 'Bosphorus Strait in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/istanbulbridge.jpg',
    width: 2268,
    height: 4032,
    alt: 'Temmuz Sehitler Bridge in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/istanbulbridge1.jpg',
    width: 3024,
    height: 4032,
    alt: 'Uskudar side of the Bosphorus Strait',
  },
  {
    src: '/static/images/turkiye/lighttower.jpg',
    width: 3024,
    height: 4032,
    alt: "Maiden's Tower in Istanbul, Turkey",
  },
  {
    src: '/static/images/turkiye/istanbulbeach.jpg',
    width: 4032,
    height: 2268,
    alt: 'Bakirkoy Beach in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/istanbulmetro.jpg',
    width: 3024,
    height: 4032,
    alt: 'Bakirkoy Atakoy Metro Station',
  },
  {
    src: '/static/images/turkiye/istanbulmetro1.jpg',
    width: 3024,
    height: 4032,
    alt: 'Bakirkoy Atakoy Metro Station',
  },
  {
    src: '/static/images/turkiye/konyaaltiBeach.jpg',
    width: 1170,
    height: 2080,
    alt: 'Konyaalti Beach in Antalya, Turkey',
  },
  {
    src: '/static/images/turkiye/mediterraneanSea.jpg',
    width: 3520,
    height: 1980,
    alt: 'Mediterranean Sea',
  },
  {
    src: '/static/images/turkiye/mirror.jpg',
    width: 1170,
    height: 2080,
    alt: 'Rare mirror selfie',
  },
  {
    src: '/static/images/turkiye/DudenWaterfall.jpg',
    width: 4032,
    height: 3024,
    alt: 'Duden Waterfalls in Antalya, Turkey',
  },
  {
    src: '/static/images/turkiye/eminonuSquare.jpg',
    width: 3024,
    height: 4032,
    alt: 'Eminonu Square in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/galataBridge.jpg',
    width: 3024,
    height: 4032,
    alt: 'Galata Bridge in Istanbul, Turkey',
  },
  {
    src: '/static/images/turkiye/meWithHagiaSofia.jpg',
    width: 3024,
    height: 4032,
    alt: 'Me with Hagia Sophia',
  },
  {
    src: '/static/images/turkiye/meAtBlueMosque.jpg',
    width: 3024,
    height: 4032,
    alt: 'Me at Blue Mosque in Istanbul, Turkey',
  },
  {
    src: '/static/images/singapore/cairo.jpg',
    width: 3024,
    height: 4032,
    alt: 'Egyptian cuisine in Singapore 🇸🇬',
  },
  {
    src: '/static/images/singapore/cave.jpg',
    width: 1170,
    height: 2080,
    alt: 'Fort Canning Park in Singapore 🇸🇬',
  },
  {
    src: '/static/images/singapore/chinatown.jpg',
    width: 3024,
    height: 4032,
    alt: 'Chinatown in Singapore 🇸🇬',
  },
  {
    src: '/static/images/singapore/diving.jpg',
    width: 1170,
    height: 2080,
    alt: 'Diving experience',
  },
  {
    src: '/static/images/singapore/gardenByTheBay.jpg',
    width: 3024,
    height: 4032,
    alt: 'Garden by the Bay in Singapore 🇸🇬',
  },
  {
    src: '/static/images/singapore/gardenByTheBay2.jpg',
    width: 3024,
    height: 4032,
    alt: 'Garden by the Bay Light Show',
  },
  {
    src: '/static/images/singapore/grand_prix.jpg',
    width: 3024,
    height: 4032,
    alt: 'Singapore Grand Prix Night Race',
  },
  {
    src: '/static/images/singapore/jewel.jpg',
    width: 3024,
    height: 4032,
    alt: 'Jewel in Singapore 🇸🇬 - One of the best airports in the world',
  },
  {
    src: '/static/images/singapore/marina_bay.jpg',
    width: 3024,
    height: 4032,
    alt: 'Marina Bay Sands',
  },
  {
    src: '/static/images/singapore/marina_bay_2.jpg',
    width: 3024,
    height: 4032,
    alt: 'Another view of Marina Bay Sands',
  },
  {
    src: '/static/images/singapore/merlion.jpg',
    width: 4032,
    height: 3024,
    alt: 'Merlion in Singapore 🇸🇬',
  },
  {
    src: '/static/images/singapore/sentosa.jpg',
    width: 2268,
    height: 4032,
    alt: 'Sentosa Island Cable Car',
  },
  { src: '/static/images/singapore/siloso.jpg', width: 4032, height: 3024, alt: 'Siloso Beach' },
  {
    src: '/static/images/singapore/skyline.jpg',
    width: 4032,
    height: 3024,
    alt: 'Singapore Skyline',
  },
  {
    src: '/static/images/singapore/universal_studio.jpg',
    width: 3024,
    height: 4032,
    alt: 'Roaring with tigers at Universal Studios 🇸🇬',
  },
  {
    src: '/static/images/singapore/universal_studio_2.jpg',
    width: 3840,
    height: 2160,
    alt: 'Teaching dance steps to Singaporean friends',
  },
  {
    src: '/static/images/singapore/universal_studio_3.jpg',
    width: 3024,
    height: 4032,
    alt: 'No seats available in the taxi',
  },
  {
    src: '/static/images/singapore/universal_studio_4.jpg',
    width: 3024,
    height: 4032,
    alt: 'Is anyone inside?',
  },
  {
    src: '/static/images/singapore/universal_studio_5.jpg',
    width: 3024,
    height: 4032,
    alt: 'I got arrested at Universal Studios 🇸🇬',
  },
  { src: '/static/images/singapore/wheel.jpg', alt: 'Singapore Flyer' },
  { src: '/static/images/malaysia/batucave.jpg', alt: 'Batu Caves in Malaysia' },
  { src: '/static/images/malaysia/batucave1.jpg', alt: 'Batu Caves with friends in Malaysia' },
  {
    src: '/static/images/malaysia/chinatown.jpg',
    width: 3024,
    height: 4032,
    alt: 'These are the nights I will never forget',
  },
  { src: '/static/images/malaysia/market.jpg', alt: 'Chinatown Market in Kuala Lumpur' },
  {
    src: '/static/images/malaysia/medreka.jpg',
    width: 1170,
    height: 2080,
    alt: 'Merdeka 118 Tower - 2nd Tallest Building in the World',
  },
  { src: '/static/images/malaysia/monorail.jpg', alt: 'Monorail in Kuala Lumpur' },
  {
    src: '/static/images/malaysia/nationalmosque.jpg',
    width: 3024,
    height: 4032,
    alt: 'Friday Prayer at the National Mosque of Malaysia 🇲🇾',
  },
  { src: '/static/images/malaysia/petronas.jpg', alt: 'Water show at KLCC 🇲🇾' },
  {
    src: '/static/images/malaysia/petronas2.jpg',
    width: 3024,
    height: 4032,
    alt: 'Kuala Lumpur from the 34th Floor Penthouse at Night',
  },
  {
    src: '/static/images/malaysia/kualaLumpur.jpg',
    width: 1170,
    height: 2080,
    alt: 'Kuala Lumpur from the 34th Floor Penthouse in the Morning',
  },
  {
    src: '/static/images/malaysia/petronastwin.jpg',
    width: 3024,
    height: 4032,
    alt: 'When you ask a stranger to take your photo and it turns out great',
  },
  { src: '/static/images/malaysia/twintower.jpg', alt: 'Petronas Twin Towers 🇲🇾' },
  { src: '/static/images/malaysia/twintower1.jpg', alt: 'Petronas Twin Towers 🇲🇾' },
  { src: '/static/images/malaysia/batikBintang.jpg', alt: 'Batik Bintang in Kuala Lumpur 🇲🇾' },
  {
    src: '/static/images/saudiarabia/clockTower.jpg',
    width: 3024,
    height: 4032,
    alt: 'Clock Tower in Makkah',
  },
  {
    src: '/static/images/saudiarabia/harmaimTrain.jpg',
    width: 3024,
    height: 4032,
    alt: 'Haramain Train from Makkah to Madina',
  },
  { src: '/static/images/saudiarabia/kaaba.jpg', alt: 'Masjid Al-Haram' },
  { src: '/static/images/saudiarabia/kaabashareef.jpg', alt: 'Masjid Al-Haram' },
  {
    src: '/static/images/saudiarabia/madina.jpg',
    width: 3024,
    height: 4032,
    alt: 'Masjid An-Nabawi',
  },
  {
    src: '/static/images/saudiarabia/madinaTower.jpg',
    width: 3024,
    height: 4032,
    alt: 'Masjid An-Nabawi',
  },
  {
    src: '/static/images/saudiarabia/makkastreet.jpg',
    width: 3024,
    height: 4032,
    alt: 'Makkah Street',
  },
  {
    src: '/static/images/saudiarabia/nightAtKaabaComplex.jpg',
    width: 3024,
    height: 4032,
    alt: 'Night view of Kaaba Complex',
  },
  {
    src: '/static/images/saudiarabia/prophetMosqu.jpg',
    width: 3024,
    height: 4032,
    alt: 'Prophet Muhammad Mosque',
  },
  {
    src: '/static/images/saudiarabia/umrah.jpg',
    width: 3024,
    height: 4032,
    alt: 'Performing my first Umrah on January 2nd, 2025',
  },
  // OMAN
  // {
  //   src: '/static/images/oman/GX011772.mp4',
  //   type: 'video',
  //   alt: 'Driving through Muscat',
  // },
  {
    src: '/static/images/oman/snorkel_1.JPG',
    width: 5568,
    height: 4872,
    alt: 'Family of Sea Turtle',
  },
  {
    src: '/static/images/oman/snorkel_2.JPG',
    width: 5568,
    height: 4872,
    alt: 'Filming a sea turtle, turtle is actor here',
  },
  { src: '/static/images/oman/snorkel_3.JPG', width: 5568, height: 4872, alt: 'Sea Turtle' },
  {
    src: '/static/images/oman/wadis_1.JPG',
    width: 5568,
    height: 4872,
    alt: 'Between the wadis of Shab',
  },
  {
    src: '/static/images/oman/wadis_2.JPG',
    width: 5568,
    height: 4872,
    alt: 'Wadi Shab',
  },
  {
    src: '/static/images/oman/wadis_3.JPG',
    width: 5568,
    height: 4872,
    alt: 'Hiking through these mountains of Wadi Shab',
  },
  {
    src: '/static/images/oman/wadis_4.JPG',
    width: 5568,
    height: 4872,
    alt: 'Ready to hike and swim through Wadi Shab',
  },
  {
    src: '/static/images/oman/mutrah_fort_1.jpg',
    width: 3024,
    height: 4032,
    alt: 'Me, sunset and Mutrah Fort',
  },
  {
    src: '/static/images/oman/mutrah_fort_2.jpg',
    width: 3024,
    height: 4032,
    alt: 'On Mutrah Fort',
  },
  { src: '/static/images/oman/nizwa_fort_1.jpg', width: 4284, height: 5712, alt: 'Nizwa Fort' },
  {
    src: '/static/images/oman/nizwa_fort_2.jpg',
    width: 3024,
    height: 4032,
    alt: 'Nizwa Fort gate',
  },
  {
    src: '/static/images/oman/city_1.jpg',
    width: 4032,
    height: 3024,
    alt: 'Scenic view while driving to Nizwa',
  },
  { src: '/static/images/oman/tiwi_1.jpg', width: 4032, height: 3024, alt: 'Tiwi city' },
  { src: '/static/images/oman/mutrah_3.jpg', width: 3024, height: 4032, alt: 'Mutrah' },
  {
    src: '/static/images/oman/mutrah_corniche.jpg',
    width: 3024,
    height: 4032,
    alt: 'Mutrah Corniche',
  },
  {
    src: '/static/images/oman/mutrah_1.jpg',
    width: 3024,
    height: 4032,
    alt: 'Mutrah during sunset',
  },
  {
    src: '/static/images/oman/mutrah_2.jpg',
    width: 3024,
    height: 4032,
    alt: 'Mutrah Muscat, Oman',
  },
  { src: '/static/images/oman/date_tree.jpg', width: 3024, height: 4032, alt: 'Date tree' },
  {
    src: '/static/images/oman/driving.jpg',
    width: 3024,
    height: 4032,
    alt: 'Driving through the cities and highways',
  },
  {
    src: '/static/images/oman/bimmah_sinkhole.jpg',
    width: 2268,
    height: 4032,
    alt: 'Bimmah Sinkhole',
  },
  { src: '/static/images/oman/sinkhole.jpg', width: 3024, height: 4032, alt: 'Bimmah Sinkhole' },
  {
    src: '/static/images/oman/moutains.jpg',
    width: 3024,
    height: 4032,
    alt: 'Somewhere in nowhere',
  },
  {
    src: '/static/images/oman/sultan_qaboos_mosque.jpg',
    width: 3024,
    height: 4032,
    alt: 'Sultan Qaboos Grand Mosque',
  },
  {
    src: '/static/images/oman/royal_opera_house.jpg',
    width: 3024,
    height: 4032,
    alt: 'Royal Opera House',
  },
  {
    src: '/static/images/oman/hongqi_h5.jpg',
    width: 3024,
    height: 4032,
    alt: 'Car I drove over 1000km',
  },
  // EGYPT
  {
    src: '/static/images/egypt/IMG_1003.jpg',
    width: 2990,
    height: 1682,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1028.jpg',
    width: 2990,
    height: 1682,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1083.jpg',
    width: 2268,
    height: 4032,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1270.jpg',
    width: 4236,
    height: 2383,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1290.jpg',
    width: 2268,
    height: 4032,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1458.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1491.jpg',
    width: 4236,
    height: 2383,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1525.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1527.jpg',
    width: 3974,
    height: 2235,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1544.jpg',
    width: 4283,
    height: 2409,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1554.jpg',
    width: 2754,
    height: 4896,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1560.jpg',
    width: 4236,
    height: 2383,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1565.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1571.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1593.jpg',
    width: 4236,
    height: 2383,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1603.jpg',
    width: 4895,
    height: 2753,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1620.jpg',
    width: 4236,
    height: 2383,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1631.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1704.jpg',
    width: 2268,
    height: 4032,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1708.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1757.jpg',
    width: 1980,
    height: 3520,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1797.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1874.jpg',
    width: 5712,
    height: 3213,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1877.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1891.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1896.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1924.jpg',
    width: 1980,
    height: 3520,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1935.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1943.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1945.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1953_2.jpg',
    width: 4896,
    height: 2754,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1957_2.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1974.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1979.jpg',
    width: 1356,
    height: 2412,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_1998.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_2055.jpg',
    width: 5712,
    height: 3213,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_2056.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_2059.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_2086.jpg',
    width: 1980,
    height: 3520,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_2106.jpg',
    width: 1980,
    height: 3520,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_2140.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_2280.jpg',
    width: 3213,
    height: 5712,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_2362_2.jpg',
    width: 4236,
    height: 2383,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_2410.jpg',
    width: 2268,
    height: 4032,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_2571_2.jpg',
    width: 1206,
    height: 669,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_2572.jpg',
    width: 1206,
    height: 683,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_4739.jpg',
    width: 1206,
    height: 2131,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_9722.JPG',
    width: 4032,
    height: 3024,
    alt: 'Egypt',
  },
  {
    src: '/static/images/egypt/IMG_9728.JPG',
    width: 5712,
    height: 4284,
    alt: 'Egypt',
  },
]
